import { PresetChat } from '../../types';

export const presetChats: PresetChat[] = [
  {
    id: 'preset-companion',
    name: 'AI Companion',
    description: 'A one-on-one chat with your general-purpose AI assistant.',
    participantIds: ['default-companion'],
    discussionMode: 'moderated',
    isDefault: true,
  },
  {
    id: 'preset-brainstorm',
    name: 'Brainstorming Crew',
    description: 'Generate and refine ideas with a diverse team of creative thinkers.',
    participantIds: ['brainstorm-contrarian', 'brainstorm-connector', 'default-visionary', 'brainstorm-architect'],
    discussionMode: 'moderated',
    isDefault: true,
  },
   {
    id: 'preset-debate',
    name: 'Decision Board',
    description: 'Explore topics from multiple viewpoints with a Pragmatist, Visionary, and Ethicist to make a decision.',
    participantIds: ['default-pragmatist', 'default-visionary', 'default-ethicist'],
    discussionMode: 'moderated',
    isDefault: true,
  },
  {
    id: 'preset-dreamers',
    name: 'The Dreamers',
    description: 'A lively group for pure, unfiltered imagination and wild ideas.',
    participantIds: ['default-visionary', 'brainstorm-connector', 'default-creative-writer'],
    discussionMode: 'moderated',
  },
  {
    id: 'preset-socratic',
    name: 'Socratic Circle',
    description: 'Engage in deep philosophical discussions and explore complex ethical questions.',
    participantIds: ['brainstorm-philosopher', 'default-ethicist', 'brainstorm-contrarian'],
    discussionMode: 'turn_based',
  },
  {
    id: 'preset-writers-room',
    name: "Writers' Room",
    description: 'Collaborate on stories, scripts, and plot points with a dedicated creative team.',
    participantIds: ['default-creative-writer', 'brainstorm-architect', 'brainstorm-connector'],
    discussionMode: 'moderated',
  },
   {
    id: 'preset-comedy',
    name: 'Comedy Sketch Crew',
    description: 'Generate jokes, funny scenarios, and humorous dialogue with a witty trio.',
    participantIds: ['default-jester', 'default-creative-writer', 'brainstorm-contrarian'],
    discussionMode: 'turn_based',
  },
  {
    id: 'preset-tech',
    name: 'Tech Review Board',
    description: 'Get feedback on technical ideas, code, and architecture from a pragmatic perspective.',
    participantIds: ['default-code-assistant', 'default-pragmatist', 'brainstorm-architect'],
    discussionMode: 'moderated',
  },
  {
    id: 'preset-strategy',
    name: 'Strategy Unit',
    description: 'For business, planning, and tactical problem-solving with a focus on clear outcomes.',
    participantIds: ['default-pragmatist', 'brainstorm-architect', 'default-code-assistant'],
    discussionMode: 'turn_based',
  },
   {
    id: 'preset-history',
    name: 'Historical Analysis',
    description: 'Understand modern problems and future possibilities through the lens of the past.',
    participantIds: ['default-historian', 'default-ethicist', 'default-pragmatist'],
    discussionMode: 'moderated',
  },
  {
    id: 'preset-marketing',
    name: 'Marketing Pitch Team',
    description: 'Develop and refine marketing angles, slogans, and campaign strategies.',
    participantIds: ['default-visionary', 'default-pragmatist', 'default-creative-writer'],
    discussionMode: 'moderated',
  },
  {
    id: 'preset-growth',
    name: 'Personal Growth Council',
    description: 'A supportive group for self-reflection, personal development, and understanding your own thoughts.',
    participantIds: ['default-companion', 'brainstorm-philosopher', 'default-ethicist'],
    discussionMode: 'turn_based',
  },
  {
    id: 'preset-creative-council',
    name: 'Creative Council',
    description: 'Brainstorm ad copy, social media posts, and novel ideas with a team of creative specialists.',
    participantIds: ['default-creative-writer', 'default-visionary', 'default-companion'],
    discussionMode: 'moderated',
  },
];